# Generated by Django 4.2.15 on 2024-08-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dishname', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
